name: ScheduleTest

on:
  push:
   branches:
     - DevPipelienes
  schedule:
    - cron: '5 * * * *'

jobs:
  build-gradle-project:
   runs-on: ubuntu-latest
   steps:
   - name: Scheduling test
     shell: bash
     run: |
       echo "This is testing"
