name: ScheduleTest

on:
  schedule:
  - cron: '*/2 * * * *'

jobs:
  build-gradle-project:
   runs-on: ubuntu-latest
   steps:
   - name: Scheduling test
     shell: bash
     run: |
      echo "This is testing"
